create table "public"."link_previews" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "title" text,
    "description" text,
    "image" text,
    "site_name" text,
    "hostname" text,
    "favicon" text,
    "url" text
);


alter table "public"."link_previews" enable row level security;

CREATE UNIQUE INDEX "link_previews_pkey" ON public."link_previews" USING btree (id);

alter table "public"."link_previews" add constraint "link_previews_pkey" PRIMARY KEY using index "link_previews_pkey";

create policy "Enable insert for authenticated users only"
on "public"."link_previews"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."link_previews"
as permissive
for select
to authenticated
using (true);



