create table "public"."linkPreviews" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "title" text,
    "description" text,
    "image" text,
    "site_name" text,
    "hostname" text,
    "favicon" text,
    "url" text
);


alter table "public"."linkPreviews" enable row level security;

CREATE UNIQUE INDEX "linkPreviews_pkey" ON public."linkPreviews" USING btree (id);

alter table "public"."linkPreviews" add constraint "linkPreviews_pkey" PRIMARY KEY using index "linkPreviews_pkey";

create policy "Enable insert for authenticated users only"
on "public"."linkPreviews"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."linkPreviews"
as permissive
for select
to authenticated
using (true);



